# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\"9\n\x03Raw\x12\x10\n\x08\x63\x61meraID\x18\x01 \x01(\t\x12\r\n\x05\x66rame\x18\x02 \x01(\x0c\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"L\n\x06Result\x12\x10\n\x08\x63\x61meraID\x18\x01 \x01(\t\x12\r\n\x05\x66rame\x18\x02 \x01(\x0c\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x0e\n\x06result\x18\x04 \x01(\tb\x06proto3')



_RAW = DESCRIPTOR.message_types_by_name['Raw']
_RESULT = DESCRIPTOR.message_types_by_name['Result']
Raw = _reflection.GeneratedProtocolMessageType('Raw', (_message.Message,), {
  'DESCRIPTOR' : _RAW,
  '__module__' : 'schema_pb2'
  # @@protoc_insertion_point(class_scope:Raw)
  })
_sym_db.RegisterMessage(Raw)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'schema_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  })
_sym_db.RegisterMessage(Result)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RAW._serialized_start=16
  _RAW._serialized_end=73
  _RESULT._serialized_start=75
  _RESULT._serialized_end=151
# @@protoc_insertion_point(module_scope)
