# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kafka-message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13kafka-message.proto\".\n\x0cKafkaMessage\x12\x10\n\x08\x63\x61meraID\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x62\x06proto3')



_KAFKAMESSAGE = DESCRIPTOR.message_types_by_name['KafkaMessage']
KafkaMessage = _reflection.GeneratedProtocolMessageType('KafkaMessage', (_message.Message,), {
  'DESCRIPTOR' : _KAFKAMESSAGE,
  '__module__' : 'kafka_message_pb2'
  # @@protoc_insertion_point(class_scope:KafkaMessage)
  })
_sym_db.RegisterMessage(KafkaMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KAFKAMESSAGE._serialized_start=23
  _KAFKAMESSAGE._serialized_end=69
# @@protoc_insertion_point(module_scope)
